import PDFDocument from 'pdfkit';
function slugify(input) {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'lesson'
  );
}
function formatDate(iso) {
  try {
    return new Date(iso).toISOString().slice(0, 10);
  } catch {
    return iso;
  }
}
function drawSection(doc, title, body, options = {}) {
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold').fontSize(13).fillColor('#1f2937').text(title);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(11).fillColor('#1f2937');
  if (options.bullets) {
    const lines = body
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean);
    for (const line of lines) {
      doc.text(line, { indent: 12, paragraphGap: 2 });
    }
  } else {
    doc.text(body, { align: 'left', lineGap: 2 });
  }
  doc.fillColor('#000');
}
export function buildLessonFilename(lesson) {
  return `lesson-${slugify(lesson.theme)}-${formatDate(lesson.createdAt)}.pdf`;
}
export function streamLessonPdf(lesson, res) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const filename = buildLessonFilename(lesson);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Cache-Control', 'no-store');
  doc.on('error', (err) => {
    if (!res.headersSent) {
      res.status(500).json({ error: { code: 'INTERNAL', message: 'PDF generation failed' } });
    } else {
      res.end();
    }
    // eslint-disable-next-line no-console
    console.error('PDF stream error:', err);
  });
  doc.pipe(res);
  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor('#111827')
    .text(lesson.theme, { align: 'center' });
  doc.moveDown(0.4);
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#6b7280')
    .text(
      `Age group: ${lesson.ageGroup}    ·    Date: ${formatDate(lesson.createdAt)}    ·    Source: ${lesson.source}`,
      { align: 'center' },
    );
  doc.moveDown(0.3);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
  doc.fillColor('#000');
  const c = lesson.lessonContent;
  drawSection(doc, 'Learning Objective', c.objective);
  drawSection(doc, 'Activity', c.activity);
  drawSection(doc, 'Rhyme', c.rhyme);
  drawSection(doc, 'Worksheet Idea', c.worksheet);
  drawSection(doc, 'Materials Required', c.materials.map((m) => `• ${m}`).join('\n'), {
    bullets: true,
  });
  doc.moveDown(2);
  doc
    .font('Helvetica-Oblique')
    .fontSize(8)
    .fillColor('#9ca3af')
    .text(`Generated by AI Lesson Plan Generator on ${new Date().toISOString().slice(0, 10)}`, {
      align: 'center',
    });
  doc.end();
}
